FROM python:3.9-slim

# Installa build tools + wget per scaricare astrolog
RUN apt-get update && apt-get install -y \
    git \
    gcc \
    build-essential \
    libc-dev \
    wget \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Scarica il binario astrolog e rendilo eseguibile
RUN wget https://www.astrolog.org/ftp/astrolog.linux -O /app/astrolog && chmod +x /app/astrolog

CMD ["python", "app.py"]
