
services:
  - type: web
    name: astrology-human-design-bundle
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: true
